---
- name: CMDB Mac Setup Playbook
  hosts: localhost
  connection: local

  vars:
    - downloads: ~/.ansible-downloads/

  tasks:
    - name: Create Ansible downloads directory
      file: path={{downloads}} state=directory
    # - include: preferences/softwareupdate.yml
    # - include: preferences/dotfiles.yml
    # - include: preferences/preferences.yml

- include: apps/homebrew.yml

- include: mac_apps.yml

- include: homebrew_packages.yml

- include: python_packages.yml
